---
- name: Print degub info
  hosts: hosts
  tasks:
    - debug:
        msg: "Ansible Distribution: {{ ansible_distribution }} \n Ansible Dist version: {{ ansible_distribution_version }} \nAnsible Vars: {{ ansible_env }}"
- name: Install Work Tools
  hosts: hosts
  become: False
  tasks:
    - name: 'Installation'
      become: True
      package:
        name:
          - sbsigntools
        update_cache: True
