font:
  normal:
    family: MesloLGL Nerd Font
    style: Regular

  bold:
    family: MesloLGL Nerd Font
    style: Bold

  italic:
    family: MesloLGL Nerd Font
    style: Italic

  bold_italic:
    family: MesloLGL Nerd Font
    style: Bold Italic

  size: 14
