- name: Install Pyenv
  hosts: sandboxes
  tasks:
    - name: Clone pyenv
      ansible.builtin.git:
        repo: https://github.com/pyenv/pyenv.git 
        dest: "{{ ansible_env.HOME }}/.pyenv"
        accept_hostkey: yes
    - name: Configure pyenv
      command: src/configure 
      args:
        chdir: "{{ ansible_env.HOME }}/.pyenv"
    - name: make pyenv
      command: make -C src 
      args:
        chdir: "{{ ansible_env.HOME }}/.pyenv"
