---
- name: Install Fonts
  hosts: sandboxes
  become: False
  tasks:
    - name: ensure fonts directory
      file:
        path: "{{ ansible_env.HOME }}/.fonts"
        state: directory
    - name: "Check if FiraCode Nerd exists"
      stat:
        path: "{{ ansible_env.HOME }}/.fonts/Fira*Code*"
      register: result

    - name: Download Fira
      when: (result.stat.isreg is undefined) or (not result.stat.isreg)
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/FiraCode.zip
        dest: "{{ ansible_env.HOME }}/.fonts/"
        remote_src: yes
    - name: Reload fonts
      command: fc-cache -f -v
- name: Install Caps Lock conversion with udevmon
  # In Fedora you have to run `make install-udevmon` given that it's not installed by default
  # refencehttps://gist.github.com/jandvanegas/2057f4ec1d4fc29d5bb3543020a7923f 
  # https://gist.github.com/jsonMartin/9690654b13863f99b9cc344bb5bf7b0f
  hosts: sandboxes
  become: False
  tasks:
    - name: "Install Packages"
      become: True
      package:
        name: 
          - cmake
          - gnome-tweaks # TODO automate
        update_cache: True
    - name: Download caps2esc
      ansible.builtin.git:
        repo: https://gitlab.com/interception/linux/plugins/caps2esc.git
        dest: "{{ ansible_env.HOME }}/caps2esc"
        accept_hostkey: yes
    - name: Build caps2esc
      command: cmake -B build -DCMAKE_BUILD_TYPE=Release
      args:
        chdir: "{{ ansible_env.HOME }}/caps2esc"
    - name: Make caps2esc
      command: cmake --build build
      args:
        chdir: "{{ ansible_env.HOME }}/caps2esc"
    - name: Create symlink for caps2esc
      become: True
      ansible.builtin.file:
        src: "{{ ansible_env.HOME }}/caps2esc/build/caps2esc"
        dest: "/usr/bin/caps2esc"
        state: link
    - name: Copy to etc
      become: True
      ansible.builtin.copy:
        src: ./udevmon/udevmon-caps2esc.yml
        dest: "/etc/udevmon-caps2esc.yml"
    - name: Add service
      become: True
      ansible.builtin.copy:
        src: ./udevmon/udevmon-caps2esc.service
        dest: "/etc/systemd/system/udevmon-caps2esc.service"
    - name: Enable service
      become: True
      command: systemctl enable udevmon-caps2esc
- name: Install Caps Lock conversion
  # Change with gnome-tweaks, udevmon and xcape
  # Xcape didn't work Todo: investigate how to run addin it to .xprofile
  hosts: disabled
  become: False
  tasks:
    - name: "Install Packages for Debian"
      become: True
      package:
        name: 
          - gnome-tweaks # TODO automate
          - git 
          - gcc 
          - make 
          - pkg-config 
        update_cache: True
    - name: "Install Packages for Debian"
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      become: True
      package:
        name: 
          - libx11-dev 
          - libxtst-dev 
          - libxi-dev
        update_cache: True
    - name: "Install Packages for Fedora"
      become: True
      when: ansible_distribution == 'Fedora'
      package:
        name: 
          - libX11-devel 
          - libXtst-devel 
          - libXi-devel
        update_cache: True
    - name: Download xcape
      ansible.builtin.git:
        repo: https://github.com/alols/xcape.git 
        dest: "{{ ansible_env.HOME }}/xcape"
        accept_hostkey: yes
    - name: Make xcape
      command: make
      args:
        chdir: "{{ ansible_env.HOME }}/xcape"
    - name: Install xcape
      become: True
      command: make install
      args:
        chdir: "{{ ansible_env.HOME }}/xcape"
