---
- name: Print degub info
  hosts: sandboxes
  tasks:
    - debug: 
        msg: "Ansible Distribution: {{ ansible_distribution }} \n Ansible Dist version: {{ ansible_distribution_version }} \nAnsible Vars: {{ ansible_env }}"
- name: Install Work Tools
  hosts: sandboxes
  become: False
  tasks:
    - name: "Installation"
      become: True
      package:
        name: 
        - google-chrome-stable
        - ulauncher
        - wmctrl # https://github.com/Ulauncher/Ulauncher/wiki/Hotkey-In-Wayland
        - wl-clipboard
        update_cache: True
    - name: Add flatpak
      become: True
      community.general.flatpak_remote:
        name: flathub2
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    - name: Install defaults
      community.general.flatpak:
        name: 
        - com.slack.Slack
        - org.telegram.desktop
        - us.zoom.Zoom 
        - com.bitwarden.desktop
        - org.mozilla.Thunderbird
        - md.obsidian.Obsidian
        - com.getpostman.Postman
        - com.calibre_ebook.calibre
        - com.visualstudio.code
        - com.todoist.Todoist
        - com.spotify.Client
        - com.github.xournalpp.xournalpp
        - org.videolan.VLC
        state: present
        method: system
# from https://www.linuxbuzz.com/how-to-install-virtualbox-on-fedora-linux/
# https://computingforgeeks.com/how-to-install-virtualbox-on-fedora-linux/
# And this to sign https://gist.github.com/reillysiemens/ac6bea1e6c7684d62f544bd79b2182a4
# Better install manually
- name: Virtual box
  hosts: disabled
  tasks:
    - name: Import public key
      become: True
      ansible.builtin.rpm_key:
        state: present
        key: https://www.virtualbox.org/download/oracle_vbox.asc 
    - name: Virtualbox yum repo
      when: ansible_distribution == 'Fedora' and ansible_distribution_version == '36'
      become: True
      ansible.builtin.copy:
        src: ./virtualbox/virtualbox-fedora-36.repo
        dest: "/etc/yum.repos.d/"
    - name: "Install Packages"
      become: True
      package:
        name: 
          - kernel-headers
          - kernel-devel
          - "VirtualBox-6.1"
          - "virtualbox-guest-additions"
          - openssl
          - libffi-devel
        update_cache: True
    - name: Create rsa key pair
      become: True
      command: bash ./sign/create.sh
- name: Vagrant
  hosts: sandboxes
  tasks:
    - name: Add repository
      when: ansible_distribution == 'Fedora'
      become: True
      ansible.builtin.yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://rpm.releases.hashicorp.com/fedora/hashicorp.repo 
    - name: "Install Packages"
      become: True
      package:
        name: 
          - vagrant
        update_cache: True
