- name: Install AWS cli
  hosts: hosts
  become: False
  tasks:
    - name: Create a if it does not exist
      ansible.builtin.file:
        path: "{{playbook_dir}}/out"
        state: directory
    - get_url:
        url="https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
        dest="{{playbook_dir}}/out/awscliv2.zip"
      register: get_aws_cli
    - debug: msg="solr was downloaded"
    - name: Unzip
      ansible.builtin.unarchive:
        src: "{{playbook_dir}}/out/awscliv2.zip" 
        dest: "{{playbook_dir}}/out/"
    - name: Install
      become: True
      ansible.builtin.command: "bash {{playbook_dir}}/out/aws/install --update"
- import_playbook: brew-playbook.yml
- name: Install AWS vault
  hosts: hosts
  become: False
  tasks:
    - community.general.homebrew:
        name: aws-vault
        state: latest
        update_homebrew: true     
