- name: Install AWS cli
  hosts: hosts
  become: False
  tasks:
    - name: Create build dir
      ansible.builtin.tempfile:
        state: directory
        suffix: temp
      register: build_dir
    - get_url:
        url="https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
        dest="{{ build_dir.path }}/awscliv2.zip"
      register: get_aws_cli
    - debug: msg="solr was downloaded"
    - name: Unzip
      ansible.builtin.unarchive:
        src: "{{build_dir.path}}/awscliv2.zip" 
        dest: "{{build_dir.path}}/"
    - name: Install
      become: True
      ansible.builtin.command: "bash {{build_dir.path}}/aws/install --update"
- import_playbook: brew-playbook.yml
- name: Install AWS vault
  hosts: hosts
  become: False
  tasks:
    - community.general.homebrew:
        name: aws-vault
        state: latest
        update_homebrew: true     
