- name: Install Brew
  hosts: hosts
  become: False
  tasks:
    - name: Create temporary build directory
      ansible.builtin.tempfile:
        state: directory
        suffix: build
      register: build_dir
    - get_url:
        url: "https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"
        dest: "{{ build_dir.path }}/brew_install.sh"
        mode: '0751'
      name: Download brew
      register: get_aws_cli
    - name: Install brew
      ansible.builtin.shell: |
        CI=1 {{ build_dir.path }}/brew_install.sh >> logs.txt
      # Dont forget to run
      # (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/javanegas/.zshrc
      # eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
