- name: Install Mongosh
  hosts: hosts
  become: True
  tasks:
  - name: Add repository
    ansible.builtin.yum_repository:
      name: mongodb-org-6.0
      description: Mongo DB Repository 6.0
      baseurl: https://repo.mongodb.org/yum/redhat/8/mongodb-org/6.0/x86_64/
      gpgcheck: yes
      enabled: yes
      gpgkey: https://www.mongodb.org/static/pgp/server-6.0.asc
  - name: 'Package Installation'
    package:
      name:
        - mongodb-mongosh
      update_cache: True

