---
- name: Print degub info
  hosts: hosts
  tasks:
    - debug:
        msg: "Ansible Distribution: {{ ansible_distribution }} \n Ansible Dist version: {{ ansible_distribution_version }} \nAnsible Vars: {{ ansible_env }}"
- name: Install Work Tools
  hosts: hosts
  become: False
  tasks:
    - name: 'System Installation'
      become: True
      package:
        name:
          - python3-nautilus # needed for gsconnect
          - nautilus-extensions # needed for gsconnect
          - google-chrome-stable
          - ulauncher
          - wmctrl # https://github.com/Ulauncher/Ulauncher/wiki/Hotkey-In-Wayland
          # - wl-clipboard -> has issues with vim yanking
          - curl
          - neofetch
          - vnstat
          # - gnome-pomodoro
          - snapd
          - ghostwriter
          - go
          - pandoc
          - texlive-xetex
          - texlive-collection-mathextra
          - waydroid
          - gh
          - nmap
          - evince
        update_cache: True
    - name: Add flatpak
      become: True
      community.general.flatpak_remote:
        name: flathub2
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    - name: Install defaults
      community.general.flatpak:
        name:
          - com.uploadedlobster.peek
          - com.slack.Slack
          - org.telegram.desktop
          - us.zoom.Zoom
          - com.bitwarden.desktop
          - org.mozilla.Thunderbird
          - md.obsidian.Obsidian
          - com.getpostman.Postman
          - com.calibre_ebook.calibre
          # - com.visualstudio.code
          - com.todoist.Todoist
          - com.spotify.Client
          - com.github.xournalpp.xournalpp
          - org.videolan.VLC
          - org.kde.kdenlive # editing videos
          - net.ankiweb.Anki
          - com.discordapp.Discord
          - org.gnome.meld
          - org.gnome.Evolution 
          - com.simplenote.Simplenote
          - org.gimp.GIMP
          - org.keepassxc.KeePassXC
          - com.syntevo.SmartGit
        state: present
        method: system
    - name: Install Snaps
      become: True
      community.general.snap:
        name:
          - superproductivity
          - llama
          - cacher
          - storage-explorer # Azure storage explorer
          - kuro-desktop
          - p3x-onenote
          - joplin-desktop
          - color-picker
    - name: Install Snaps Classic
      become: True
      community.general.snap:
        name: notable
        classic: True
- import_playbook: "nordvpn-playbook.yml"
- import_playbook: "vagrant-playbook.yml"
